package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"kanarche.eu/internal/config"
)

func TestValidateConfigAcceptsCommittedFile(t *testing.T) {
	t.Setenv(config.PathEnv, filepath.Join("..", "..", "airbg.yaml"))
	t.Setenv(config.DatabaseURLEnv, "postgres://user:pass@localhost:5432/airbg")
	var out, errOut bytes.Buffer
	if code := runValidateConfig(&out, &errOut); code != 0 {
		t.Fatalf("runValidateConfig = %d, want 0; stderr:\n%s", code, errOut.String())
	}
	if !strings.Contains(out.String(), "configuration is valid") {
		t.Errorf("stdout does not confirm validity:\n%s", out.String())
	}
}

// The command must never print a credential: it runs in CI logs.
func TestValidateConfigNeverPrintsSecrets(t *testing.T) {
	t.Setenv(config.PathEnv, filepath.Join("..", "..", "airbg.yaml"))
	t.Setenv(config.DatabaseURLEnv, "postgres://user:hunter2@localhost:5432/airbg")
	var out, errOut bytes.Buffer
	runValidateConfig(&out, &errOut)
	combined := out.String() + errOut.String()
	for _, secret := range []string{"hunter2"} {
		if strings.Contains(combined, secret) {
			t.Errorf("output contains the secret %q:\n%s", secret, combined)
		}
	}
}

func TestValidateConfigRejectsMissingFile(t *testing.T) {
	t.Setenv(config.PathEnv, filepath.Join(t.TempDir(), "absent.yaml"))
	var out, errOut bytes.Buffer
	if code := runValidateConfig(&out, &errOut); code != 1 {
		t.Fatalf("runValidateConfig = %d, want 1", code)
	}
	if !strings.Contains(errOut.String(), "cannot read") {
		t.Errorf("stderr = %q, want it to name the unreadable file", errOut.String())
	}
}

// mustFindScalar walks a mapping node down a key path and returns the scalar
// it ends at, failing the test if any step is missing or the wrong kind.
//
// yaml.Node stores a mapping as a flat Content slice of alternating key and
// value nodes, which is why this steps by two rather than indexing a map.
func mustFindScalar(t *testing.T, node *yaml.Node, path ...string) *yaml.Node {
	t.Helper()
	for i, key := range path {
		if node.Kind != yaml.MappingNode {
			t.Fatalf("%s is not a mapping, cannot look up %q", strings.Join(path[:i], "."), key)
		}
		var next *yaml.Node
		for j := 0; j+1 < len(node.Content); j += 2 {
			if node.Content[j].Value == key {
				next = node.Content[j+1]
				break
			}
		}
		if next == nil {
			t.Fatalf("key %s not found in airbg.yaml", strings.Join(path[:i+1], "."))
		}
		node = next
	}
	if node.Kind != yaml.ScalarNode {
		t.Fatalf("%s is not a scalar", strings.Join(path, "."))
	}
	return node
}

// writeInvalidRatelimitConfig generates the semantically-invalid fixture from
// the committed airbg.yaml instead of keeping a second copy of it on disk.
//
// A committed copy has to be regenerated by hand every time a key is added to
// or removed from airbg.yaml, and the day someone forgets, this test fails for
// a reason that has nothing to do with rate limiting — it points at the
// validator when the fault is a stale fixture. Generating also keeps the
// premise honest: the file under test is the real shipped config with exactly
// one value changed, so a hardcoded default cannot make it pass for the wrong
// reason.
//
// Failing loudly when the key is absent is the point of mustFindScalar. Writing
// an unmodified config would leave the caller asserting exit code 1 against a
// perfectly valid file, which reads as a validator bug.
func writeInvalidRatelimitConfig(t *testing.T) string {
	t.Helper()
	const source = "../../airbg.yaml"
	raw, err := os.ReadFile(source)
	if err != nil {
		t.Fatalf("read %s: %v", source, err)
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse %s: %v", source, err)
	}
	if len(doc.Content) != 1 {
		t.Fatalf("%s holds %d documents, want 1", source, len(doc.Content))
	}
	perSecond := mustFindScalar(t, doc.Content[0], "ratelimit", "api", "per_second")
	if perSecond.Value == "0" {
		t.Fatalf("%s already sets ratelimit.api.per_second = 0, so the generated fixture would not be invalid", source)
	}
	perSecond.Value = "0"

	out, err := yaml.Marshal(&doc)
	if err != nil {
		t.Fatalf("re-encode %s: %v", source, err)
	}
	path := filepath.Join(t.TempDir(), "invalid-ratelimit.yaml")
	if err := os.WriteFile(path, out, 0o600); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	return path
}

// A file that exists and parses but is semantically invalid must still be
// rejected: the gate exists precisely to catch this class, not just missing
// files or unset paths. The fixture is the committed airbg.yaml with
// ratelimit.api.per_second changed from its real value to 0, generated at test
// time — see writeInvalidRatelimitConfig.
func TestValidateConfigRejectsSemanticallyInvalidFile(t *testing.T) {
	t.Setenv(config.PathEnv, writeInvalidRatelimitConfig(t))
	t.Setenv(config.DatabaseURLEnv, "postgres://user:pass@localhost:5432/airbg")
	var out, errOut bytes.Buffer
	if code := runValidateConfig(&out, &errOut); code != 1 {
		t.Fatalf("runValidateConfig = %d, want 1; stdout:\n%s", code, out.String())
	}
	const want = "ratelimit.api.per_second = 0, must be greater than zero"
	if !strings.Contains(errOut.String(), want) {
		t.Errorf("stderr = %q, want it to contain %q", errOut.String(), want)
	}
}

// The committed airbg.yaml ships tiles.* empty, which is a supported
// configuration (no basemap, two listeners) — not an absence of the keys.
// An operator debugging a blank map runs validate-config first; if these
// rows were silently missing from the table, that operator would
// reasonably conclude tiles are unsupported rather than merely unconfigured.
func TestValidateConfigShowsEmptyTilesKeys(t *testing.T) {
	t.Setenv(config.PathEnv, filepath.Join("..", "..", "airbg.yaml"))
	t.Setenv(config.DatabaseURLEnv, "postgres://user:pass@localhost:5432/airbg")
	var out, errOut bytes.Buffer
	if code := runValidateConfig(&out, &errOut); code != 0 {
		t.Fatalf("runValidateConfig = %d, want 0; stderr:\n%s", code, errOut.String())
	}
	got := out.String()
	for _, key := range []string{"tiles.addr", "tiles.dir", "tiles.public_url", "tiles.archive"} {
		if !strings.Contains(got, key) {
			t.Errorf("stdout does not mention %s:\n%s", key, got)
		}
	}
}

// TestValidateConfigShowsUnscaledColour. frontend.unscaled_colour is a paint
// value reaching a GL layer, not a secret, so it belongs in the printed table
// like every other operational value an operator debugging the map needs to
// see at a glance.
func TestValidateConfigShowsUnscaledColour(t *testing.T) {
	t.Setenv(config.PathEnv, filepath.Join("..", "..", "airbg.yaml"))
	t.Setenv(config.DatabaseURLEnv, "postgres://user:pass@localhost:5432/airbg")
	var out, errOut bytes.Buffer
	if code := runValidateConfig(&out, &errOut); code != 0 {
		t.Fatalf("runValidateConfig = %d, want 0; stderr:\n%s", code, errOut.String())
	}
	if !strings.Contains(out.String(), "frontend.unscaled_colour") {
		t.Errorf("stdout does not mention frontend.unscaled_colour:\n%s", out.String())
	}
}

func TestValidateConfigRejectsUnsetPath(t *testing.T) {
	t.Setenv(config.PathEnv, "")
	var out, errOut bytes.Buffer
	if code := runValidateConfig(&out, &errOut); code != 1 {
		t.Fatalf("runValidateConfig = %d, want 1", code)
	}
	if !strings.Contains(errOut.String(), config.PathEnv) {
		t.Errorf("stderr = %q, want it to name %s", errOut.String(), config.PathEnv)
	}
}
